.TH "_closed_hash_table" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_closed_hash_table \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hashtable.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "size_t \fBcur_size\fP"
.br
.ti -1c
.RI "uint16_t \fBmax_jumps\fP"
.br
.ti -1c
.RI "int8_t \fBobjfree\fP"
.br
.ti -1c
.RI "HashNode * \fBdata\fP"
.br
.ti -1c
.RI "uint32_t(* \fBhash\fP )(void *, size_t)"
.br
.ti -1c
.RI "uint32_t(* \fBprob\fP )(uint32_t)"
.br
.ti -1c
.RI "\fBFunctor_API\fP \fBAPI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 61 of file libcgeneric/hashtable.h.
.SH "Field Documentation"
.PP 
.SS "\fBFunctor_API\fP \fBAPI\fP"
.PP
Definition at line 69 of file libcgeneric/hashtable.h.
.SS "size_t \fBcapacity\fP"
.PP
Definition at line 62 of file libcgeneric/hashtable.h.
.SS "size_t \fBcur_size\fP"
.PP
Definition at line 63 of file libcgeneric/hashtable.h.
.SS "HashNode * \fBdata\fP"
.PP
Definition at line 66 of file libcgeneric/hashtable.h.
.SS "uint32_t(* \fBhash\fP)(void *, size_t)"
.PP
Definition at line 67 of file libcgeneric/hashtable.h.
.SS "uint16_t \fBmax_jumps\fP"
.PP
Definition at line 64 of file libcgeneric/hashtable.h.
.SS "int8_t \fBobjfree\fP"
.PP
Definition at line 65 of file libcgeneric/hashtable.h.
.SS "uint32_t(* \fBprob\fP)(uint32_t)"
.PP
Definition at line 68 of file libcgeneric/hashtable.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
