.TH "_closed_hash_iterator" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_closed_hash_iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hashtable.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "HashNode * \fBptr\fP"
.br
.ti -1c
.RI "\fBCHTable\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file libcgeneric/hashtable.h.
.SH "Field Documentation"
.PP 
.SS "\fBCHTable\fP * \fBparent\fP"Pointer to the parent object 
.PP
Definition at line 84 of file libcgeneric/hashtable.h.
.SS "HashNode * \fBptr\fP"Pointer to the current entry in the hash table 
.PP
Definition at line 82 of file libcgeneric/hashtable.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
