.TH "_prio_queue" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_prio_queue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <priority_queue.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHeap\fP * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file libcgeneric/priority_queue.h.
.SH "Field Documentation"
.PP 
.SS "\fBHeap\fP * \fBdata\fP"The heap used to store the data 
.PP
Definition at line 27 of file libcgeneric/priority_queue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
