.TH "_ptr_struct" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ptr_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBobjfree\fP"
.br
.ti -1c
.RI "size_t \fBobjsize\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "struct \fB_Node\fP * \fBhead\fP"
.br
.ti -1c
.RI "struct \fB_Node\fP * \fBtail\fP"
.br
.ti -1c
.RI "struct \fB_Node\fP * \fBfree_list\fP"
.br
.ti -1c
.RI "\fBFunctor_API\fP \fBAPI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "\fBFunctor_API\fP \fBAPI\fP"
.PP
Definition at line 62 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP * \fBfree_list\fP"Pointer to free nodes 
.PP
Definition at line 61 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP * \fBhead\fP"Pointer to head of the data 
.PP
Definition at line 56 of file libcgeneric/gen/data_types.h.
.SS "uint8_t \fBobjfree\fP"Flag to determine if to free objects or not 
.PP
Definition at line 47 of file libcgeneric/gen/data_types.h.
.SS "size_t \fBobjsize\fP"Size of the objects in the struct 
.PP
Definition at line 50 of file libcgeneric/gen/data_types.h.
.SS "size_t \fBsize\fP"Size of the struct 
.PP
Definition at line 53 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP * \fBtail\fP"Pointer to tail of the data 
.PP
Definition at line 59 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
