.TH "_ptr_iter" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ptr_iter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_Node\fP * \fBptr\fP"
.br
.ti -1c
.RI "struct \fB_ptr_struct\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "struct \fB_ptr_struct\fP * \fBparent\fP"
.PP
Definition at line 67 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP * \fBptr\fP"
.PP
Definition at line 66 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
