.TH "BinaryTree" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BinaryTree \- 
.PP
flag to pass in if the data to be stored is dynamically allocated.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <binary_tree.h>\fP
.SH "Detailed Description"
.PP 
flag to pass in if the data to be stored is dynamically allocated. 

If the data passed in to a function is created dynamically, then the function will not make a copy and instead just point to the dynamically allocated memory. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
