.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/units/check_funcs.c" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/units/check_funcs.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBintcmp\fP (const void *a, const void *b, size_t x UNUSED)"
.br
.ti -1c
.RI "void \fBprint_int\fP (const void *a)"
.br
.ti -1c
.RI "void * \fBckalloc\fP (size_t size)"
.br
.ti -1c
.RI "void \fBckfree\fP (void *ptr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void* ckalloc (size_tsize)"
.PP
Definition at line 20 of file check_funcs.c.
.SS "void ckfree (void *ptr)"
.PP
Definition at line 32 of file check_funcs.c.
.SS "int32_t intcmp (const void *a, const void *b, size_t xUNUSED)"
.PP
Definition at line 2 of file check_funcs.c.
.SS "void print_int (const void *a)"
.PP
Definition at line 14 of file check_funcs.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
