.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/units/check_basevector.c" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/units/check_basevector.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <check.h>\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'gen/error_macros.h'\fP
.br
\fC#include 'check_funcs.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRUNS\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSTART_TEST\fP (test_basevector_create)"
.br
.ti -1c
.RI "END_TEST \fBSTART_TEST\fP (test_basevector_destruct)"
.br
.ti -1c
.RI "END_TEST \fBSTART_TEST\fP (test_basevector_create_destruct_loop)"
.br
.ti -1c
.RI "END_TEST \fBSTART_TEST\fP (test_basevector_create_func)"
.br
.ti -1c
.RI "END_TEST \fBSTART_TEST\fP (test_basevector_api_test)"
.br
.ti -1c
.RI "END_TEST Suite * \fBbasevector_suite\fP (void)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define RUNS   100"
.PP
Definition at line 6 of file check_basevector.c.
.SH "Function Documentation"
.PP 
.SS "END_TEST Suite* basevector_suite (void)"
.PP
Definition at line 97 of file check_basevector.c.
.SS "int main (void)"
.PP
Definition at line 111 of file check_basevector.c.
.SS "END_TEST START_TEST (test_basevector_create_destruct_loop)"
.PP
Definition at line 42 of file check_basevector.c.
.SS "END_TEST START_TEST (test_basevector_api_test)"
.PP
Definition at line 77 of file check_basevector.c.
.SS "END_TEST START_TEST (test_basevector_create_func)"
.PP
Definition at line 58 of file check_basevector.c.
.SS "START_TEST (test_basevector_create)"
.PP
Definition at line 9 of file check_basevector.c.
.SS "END_TEST START_TEST (test_basevector_destruct)"
.PP
Definition at line 27 of file check_basevector.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
