.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/src/conversions.c" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/src/conversions.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string.h>\fP
.br
\fC#include 'queue.h'\fP
.br
\fC#include 'deque.h'\fP
.br
\fC#include 'list.h'\fP
.br
\fC#include 'gen/data_types.h'\fP
.br
\fC#include 'gen/gen_macros.h'\fP
.br
\fC#include 'vector.h'\fP
.br
\fC#include 'gen/error_macros.h'\fP
.br
\fC#include 'gen/access_macros.h'\fP
.br
\fC#include 'gen/function_macros.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBconvert_function\fP(DST, SRC)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define convert_function(DST, SRC)"\fBValue:\fP
.PP
.nf
DST* to_##DST##_from_##SRC(SRC *src) {\
                DST *dst = NULL;\
                ITER(SRC)* iter = NULL;\
                void* tmpobj = NULL;\
                CHECK_VARN(src,NULL);\
                CHECK_VARA(dst = malloc(sizeof *dst),NULL);\
                memset(dst,0,sizeof *dst);\
                construct(DST,dst,dst->objsize,dst->objfree);\
                iter = create(SRC##Iter,src);\
                do {\
                        tmpobj = retrieve(SRC##Iter,iter);\
                        if(!tmpobj) {\
                                destruct(DST,dst);\
                                destroy(SRC##Iter,iter);\
                                return NULL;\
                        }\
                        convert(DST,dst,tmpobj,O(src),DYNAMIC);\
                }while(next(SRC##Iter,iter));\
                destroy(SRC##Iter,iter);\
                return dst;\
        }
.fi
.PP
Definition at line 20 of file conversions.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
