.TH "/Users/matthieuriolo/Downloads/libgenc/branches/riolo/trunk/include/deque.h" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Downloads/libgenc/branches/riolo/trunk/include/deque.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gen/data_types.h'\fP
.br
\fC#include 'gen/gen_macros.h'\fP
.br
\fC#include 'gen/function_macros.h'\fP
.br
\fC#include 'gen/function_signatures.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEQUELIST_DEFINED\fP"
.br
.ti -1c
.RI "#define \fBDEQUELIST_ITER_DEFINED\fP"
.br
.RI "\fIthe iterator object that helps traverse the deque \fP"
.ti -1c
.RI "#define \fBDEQUEVECTOR_DEFINED\fP"
.br
.ti -1c
.RI "#define \fBDEQUEVECTOR_ITER_DEFINED\fP"
.br
.ti -1c
.RI "#define \fBconvert_DequeVector\fP(A, B, C, D)   push_DequeVector((A),(B),(C),(D))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_ptr_struct\fP \fBDequeList\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB_ptr_iter\fP \fBITER\fP (\fBDequeList\fP)"
.br
.ti -1c
.RI "int8_t \fBpop_back_DequeList\fP (\fBDequeList\fP *deque)"
.br
.ti -1c
.RI "void * \fBfront_DequeList\fP (\fBDequeList\fP *deque)"
.br
.ti -1c
.RI "void * \fBback_DequeList\fP (\fBDequeList\fP *deque)"
.br
.ti -1c
.RI "int8_t \fBpush_back_DequeList\fP (\fBDequeList\fP *deque, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.ti -1c
.RI "int8_t \fBconvert_DequeList\fP (\fBDequeList\fP *deque, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.ti -1c
.RI "int8_t \fBpush_front_DequeList\fP (\fBDequeList\fP *deque, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.ti -1c
.RI "\fBcreate_iter_prototypes\fP (\fBDequeList\fP) typedef struct \fB_array_struct\fP \fBDequeVector\fP"
.br
.ti -1c
.RI "struct \fB_array_iter\fP \fBITER\fP (\fBDequeVector\fP)"
.br
.ti -1c
.RI "\fBCOMMON_FUNCTION_PROTOTYPES\fP (\fBDequeVector\fP) int8_t pop_front_DequeVector(\fBDequeVector\fP *deque)"
.br
.ti -1c
.RI "int8_t \fBpop_back_DequeVector\fP (\fBDequeVector\fP *deque)"
.br
.ti -1c
.RI "void * \fBfront_DequeVector\fP (\fBDequeVector\fP *deque)"
.br
.ti -1c
.RI "void * \fBback_DequeVector\fP (\fBDequeVector\fP *deque)"
.br
.ti -1c
.RI "int8_t \fBpush_front_DequeVector\fP (\fBDequeVector\fP *deque, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.ti -1c
.RI "int8_t \fBpush_back_DequeVector\fP (\fBDequeVector\fP *deque, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.ti -1c
.RI "int8_t \fBresize_DequeVector\fP (\fBDequeVector\fP *deque, size_t size)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define convert_DequeVector(A, B, C, D)   push_DequeVector((A),(B),(C),(D))"
.PP
Definition at line 120 of file deque.h.
.SS "#define DEQUELIST_DEFINED"
.PP
Definition at line 22 of file deque.h.
.SS "#define DEQUELIST_ITER_DEFINED"
.PP
the iterator object that helps traverse the deque 
.PP
Definition at line 31 of file deque.h.
.SS "#define DEQUEVECTOR_DEFINED"
.SS "#define DEQUEVECTOR_ITER_DEFINED"
.PP
Definition at line 107 of file deque.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_ptr_struct\fP \fBDequeList\fP"
.PP
Definition at line 23 of file deque.h.
.SH "Function Documentation"
.PP 
.SS "void* back_DequeList (\fBDequeList\fP * deque)"
.PP
Definition at line 152 of file deque.c.
.SS "void* back_DequeVector (\fBDequeVector\fP * deque)"
.PP
Definition at line 232 of file deque.c.
.SS "COMMON_FUNCTION_PROTOTYPES (\fBDequeVector\fP)"
.SS "int8_t convert_DequeList (\fBDequeList\fP * deque, void * obj, size_t objsize, int flag)"
.PP
Definition at line 58 of file deque.c.
.SS "create_iter_prototypes (\fBDequeList\fP)"
.SS "void* front_DequeList (\fBDequeList\fP * deque)"
.PP
Definition at line 144 of file deque.c.
.SS "void* front_DequeVector (\fBDequeVector\fP * deque)"
.PP
Definition at line 237 of file deque.c.
.SS "struct \fB_array_iter\fP ITER (\fBDequeVector\fP)\fC [read]\fP"
.SS "struct \fB_ptr_iter\fP ITER (\fBDequeList\fP)\fC [read]\fP"
.SS "int8_t pop_back_DequeList (\fBDequeList\fP * deque)"
.PP
Definition at line 128 of file deque.c.
.SS "int8_t pop_back_DequeVector (\fBDequeVector\fP * deque)"
.PP
Definition at line 220 of file deque.c.
.SS "int8_t push_back_DequeList (\fBDequeList\fP * deque, void * obj, size_t objsize, int flag)"
.PP
Definition at line 62 of file deque.c.
.SS "int8_t push_back_DequeVector (\fBDequeVector\fP * deque, void * obj, size_t objsize, int flag)"
.PP
Definition at line 265 of file deque.c.
.SS "int8_t push_front_DequeList (\fBDequeList\fP * deque, void * obj, size_t objsize, int flag)"
.PP
Definition at line 86 of file deque.c.
.SS "int8_t push_front_DequeVector (\fBDequeVector\fP * deque, void * obj, size_t objsize, int flag)"
.PP
Definition at line 252 of file deque.c.
.SS "int8_t resize_DequeVector (\fBDequeVector\fP * deque, size_t size)"
.PP
Definition at line 278 of file deque.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
