.TH "libcgeneric.h" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libcgeneric.h \- 
.PP
Includes the whole libgenc.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gen/access_macros.h'\fP
.br
\fC#include 'gen/control_arr_macros.h'\fP
.br
\fC#include 'gen/control_macros.h'\fP
.br
\fC#include 'gen/data_types.h'\fP
.br
\fC#include 'gen/error_macros.h'\fP
.br
\fC#include 'gen/function_macros.h'\fP
.br
\fC#include 'gen/function_signatures.h'\fP
.br
\fC#include 'gen/gen_macros.h'\fP
.br
\fC#include 'gen/stdint.h'\fP
.br
\fC#include 'binary_tree.h'\fP
.br
\fC#include 'comparisons.h'\fP
.br
\fC#include 'deque.h'\fP
.br
\fC#include 'hashtable.h'\fP
.br
\fC#include 'heap.h'\fP
.br
\fC#include 'list.h'\fP
.br
\fC#include 'node.h'\fP
.br
\fC#include 'priority_queue.h'\fP
.br
\fC#include 'queue.h'\fP
.br
\fC#include 'stack.h'\fP
.br
\fC#include 'vector.h'\fP
.br

.SH "Detailed Description"
.PP 
Includes the whole libgenc. 

Copyright 2006, All Rights Reserved, Micah Villmow 
.PP
Definition in file \fBlibcgeneric.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
