.TH "/Users/matthieuriolo/Sourcecode/libcgeneric/branches/riolo/libcgeneric/node.h" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libcgeneric/branches/riolo/libcgeneric/node.h \- 
.PP
header file for the Node implementation  

.SH SYNOPSIS
.br
.PP
\fC#include 'gen/stdint.h'\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'gen/data_types.h'\fP
.br
\fC#include 'gen/function_signatures.h'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_Node\fP \fBNode\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP * \fBconstruct_Node\fP (size_t nlinks)"
.br
.ti -1c
.RI "void \fBdestruct_Node\fP (\fBNode\fP *node)"
.br
.in -1c
.SH "Detailed Description"
.PP 
header file for the Node implementation 

Copyright 2006, Micah Villmow, All Rights Reserved
.PP
Micah Villmow 
.PP
Definition in file \fBnode.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_Node\fP \fBNode\fP"
.PP
Definition at line 15 of file node.h.
.SH "Function Documentation"
.PP 
.SS "\fBNode\fP * construct_Node (size_tnlinks)"\fBParameters:\fP
.RS 4
\fInlinks\fP the number of links the Node should have 
.RE
.PP
\fBReturns:\fP
.RS 4
an allocated Node or NULL on error 
.RE
.PP

.SS "void destruct_Node (\fBNode\fP *node)"\fBParameters:\fP
.RS 4
\fInode\fP the Node to deallocate 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
