.TH "QueueList" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueList \- 
.PP
the queue object that handles the objects and is based on a generic list data structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue.h>\fP
.SH "Detailed Description"
.PP 
the queue object that handles the objects and is based on a generic list data structure 

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
