.TH "StackList" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StackList \- 
.PP
The stack object that handles the objects and is based on a list generic data structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack.h>\fP
.SH "Detailed Description"
.PP 
The stack object that handles the objects and is based on a list generic data structure. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
