.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/tests/vec_test.c" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/tests/vec_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'vector.h'\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'gen/error_macros.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRUNS\fP   10000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define RUNS   10000"
.PP
Definition at line 6 of file vec_test.c.
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
Definition at line 10 of file vec_test.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
