.TH "_array_struct" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_array_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "size_t \fBobjsize\fP"
.br
.ti -1c
.RI "uint8_t \fBobjfree\fP"
.br
.ti -1c
.RI "void * \fBmem\fP"
.br
.ti -1c
.RI "void * \fBend\fP"
.br
.ti -1c
.RI "void * \fBhead\fP"
.br
.ti -1c
.RI "void * \fBtail\fP"
.br
.ti -1c
.RI "\fBFunctor_API\fP \fBAPI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "\fBFunctor_API\fP \fBAPI\fP"
.PP
Definition at line 116 of file libcgeneric/gen/data_types.h.
.SS "size_t \fBcapacity\fP"Number of allocated nodes 
.PP
Definition at line 99 of file libcgeneric/gen/data_types.h.
.SS "void * \fBend\fP"Pointer to the last piece of allocated memory 
.PP
Definition at line 108 of file libcgeneric/gen/data_types.h.
.SS "void * \fBhead\fP"Pointer to the first slot of the vector 
.PP
Definition at line 111 of file libcgeneric/gen/data_types.h.
.SS "void * \fBmem\fP"Pointer to the allocated memory so that head and tail can move around 
.PP
Definition at line 106 of file libcgeneric/gen/data_types.h.
.SS "uint8_t \fBobjfree\fP"Flag to determine if to free objects or not 
.PP
Definition at line 104 of file libcgeneric/gen/data_types.h.
.SS "size_t \fBobjsize\fP"Size of the object in the vector 
.PP
Definition at line 102 of file libcgeneric/gen/data_types.h.
.SS "size_t \fBsize\fP"Size of the vector 
.PP
Definition at line 96 of file libcgeneric/gen/data_types.h.
.SS "void * \fBtail\fP"Pointer to the first available slot of the vector 
.PP
Definition at line 114 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
