.TH "_array_iter" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_array_iter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "struct \fB_array_struct\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "struct \fB_array_struct\fP * \fBparent\fP"Pointer to the currently assigned vector 
.PP
Definition at line 125 of file libcgeneric/gen/data_types.h.
.SS "void * \fBptr\fP"Pointer to the current data item 
.PP
Definition at line 122 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
