.TH "_bfs_iter" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_bfs_iter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_Node\fP * \fBptr\fP"
.br
.ti -1c
.RI "struct \fB_ptr_struct\fP \fBqueue\fP"
.br
.ti -1c
.RI "struct \fB_ptr_struct\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "struct \fB_ptr_struct\fP * \fBparent\fP"Pointer to the parent object 
.PP
Definition at line 78 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP * \fBptr\fP"Pointer to the current node 
.PP
Definition at line 72 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_ptr_struct\fP \fBqueue\fP"Queue is used for getting to the next node if queue is empty, then we are at the end of the tree 
.PP
Definition at line 76 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
