.TH "_dfs_iter" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_dfs_iter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_Node\fP * \fBptr\fP"
.br
.ti -1c
.RI "struct \fB_ptr_struct\fP \fBstack\fP"
.br
.ti -1c
.RI "struct \fB_ptr_struct\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "struct \fB_ptr_struct\fP * \fBparent\fP"Pointer to the parent object 
.PP
Definition at line 89 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP * \fBptr\fP"Pointer to the current node 
.PP
Definition at line 83 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_ptr_struct\fP \fBstack\fP"Stack is used for getting to the next node If the stack is empty, then we are at the end of the tree 
.PP
Definition at line 87 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
