.TH "_Hash_Node" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Hash_Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int8_t \fBflags\fP"
.br
.ti -1c
.RI "size_t \fBobjsize\fP"
.br
.ti -1c
.RI "void * \fBobjptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "int8_t \fBflags\fP"Flags on whether the object is created from static of dynamic data 
.PP
Definition at line 142 of file libcgeneric/gen/data_types.h.
.SS "void * \fBobjptr\fP"Pointer to the memory that holds the object 
.PP
Definition at line 146 of file libcgeneric/gen/data_types.h.
.SS "size_t \fBobjsize\fP"Size of element being stored at the node 
.PP
Definition at line 144 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
