.TH "_Node" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <data_types.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.ti -1c
.RI "void * \fBobjptr\fP"
.br
.ti -1c
.RI "struct \fB_Node\fP ** \fBptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data Structures 
.PP
Definition at line 31 of file libcgeneric/gen/data_types.h.
.SH "Field Documentation"
.PP 
.SS "uint8_t \fBflags\fP"Flags for this particular struct \fB_Node\fP 
.PP
Definition at line 34 of file libcgeneric/gen/data_types.h.
.SS "void * \fBobjptr\fP"Pointer to the object 
.PP
Definition at line 37 of file libcgeneric/gen/data_types.h.
.SS "struct \fB_Node\fP ** \fBptr\fP"Pointer to the links 
.PP
Definition at line 40 of file libcgeneric/gen/data_types.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
