.TH "_open_hash_iterator" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_open_hash_iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hashtable.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBHashListNode\fP * \fBptr\fP"
.br
.ti -1c
.RI "\fBHashListNode\fP * \fBnptr\fP"
.br
.ti -1c
.RI "\fBOHTable\fP * \fBparent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file libcgeneric/hashtable.h.
.SH "Field Documentation"
.PP 
.SS "\fBHashListNode\fP * \fBnptr\fP"Pointer to the current node in the entry 
.PP
Definition at line 50 of file libcgeneric/hashtable.h.
.SS "\fBOHTable\fP * \fBparent\fP"Pointer to the parent object 
.PP
Definition at line 52 of file libcgeneric/hashtable.h.
.SS "\fBHashListNode\fP * \fBptr\fP"Pointer to the current entry in the hash table 
.PP
Definition at line 48 of file libcgeneric/hashtable.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
