.TH "_prio_queue_node" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_prio_queue_node \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <priority_queue.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBpriority\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBdatasize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file libcgeneric/priority_queue.h.
.SH "Field Documentation"
.PP 
.SS "void * \fBdata\fP"Pointer to the data 
.PP
Definition at line 20 of file libcgeneric/priority_queue.h.
.SS "size_t \fBdatasize\fP"Size of the data being stored 
.PP
Definition at line 22 of file libcgeneric/priority_queue.h.
.SS "int32_t \fBpriority\fP"Priority value for given data 
.PP
Definition at line 18 of file libcgeneric/priority_queue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
