.TH "/Users/matthieuriolo/Downloads/libgenc/branches/riolo/trunk/include/comparisons.h" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Downloads/libgenc/branches/riolo/trunk/include/comparisons.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCMPFUNC_PROTO\fP(TYPE)   int TYPE##cmp(void *, void *, size_t)"
.br
.RI "\fImacro to expand to the comparison function prototype \fP"
.ti -1c
.RI "#define \fBCMPFUNC_IMPL\fP(TYPE)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (char)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (float)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (double)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (int8_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (int16_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (int32_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (int64_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (uint8_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (uint16_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (uint32_t)"
.br
.ti -1c
.RI "\fBCMPFUNC_PROTO\fP (uint64_t)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int TYPE return TYPE first TYPE \fBsecond\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define CMPFUNC_IMPL(TYPE)"
.PP
Definition at line 13 of file comparisons.h.
.SS "#define CMPFUNC_PROTO(TYPE)   int TYPE##cmp(void *, void *, size_t)"
.PP
macro to expand to the comparison function prototype 
.PP
Definition at line 12 of file comparisons.h.
.SH "Function Documentation"
.PP 
.SS "CMPFUNC_PROTO (char)"
.SS "CMPFUNC_PROTO (uint64_t)"
.SS "CMPFUNC_PROTO (uint32_t)"
.SS "CMPFUNC_PROTO (uint16_t)"
.SS "CMPFUNC_PROTO (uint8_t)"
.SS "CMPFUNC_PROTO (int64_t)"
.SS "CMPFUNC_PROTO (int32_t)"
.SS "CMPFUNC_PROTO (int16_t)"
.SS "CMPFUNC_PROTO (int8_t)"
.SS "CMPFUNC_PROTO (double)"
.SS "CMPFUNC_PROTO (float)"
.SH "Variable Documentation"
.PP 
.SS "int TYPE return TYPE first TYPE \fBsecond\fP"
.PP
Definition at line 15 of file comparisons.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
