.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/config.h" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LIMITS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PTRDIFF_T\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDDEF_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBLT_OBJDIR\fP   '.libs/'"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'libcgeneric'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'villmow@gmail.com'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'libcgeneric'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'libcgeneric 0.4.2'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'libcgeneric'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '0.4.2'"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '0.4.2'"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define HAVE_DLFCN_H   1"
.PP
Definition at line 5 of file config.h.
.SS "#define HAVE_INTTYPES_H   1"
.PP
Definition at line 8 of file config.h.
.SS "#define HAVE_LIMITS_H   1"
.PP
Definition at line 11 of file config.h.
.SS "#define HAVE_MALLOC   1"
.PP
Definition at line 15 of file config.h.
.SS "#define HAVE_MEMORY_H   1"
.PP
Definition at line 18 of file config.h.
.SS "#define HAVE_MEMSET   1"
.PP
Definition at line 21 of file config.h.
.SS "#define HAVE_PTRDIFF_T   1"
.PP
Definition at line 24 of file config.h.
.SS "#define HAVE_STDDEF_H   1"
.PP
Definition at line 27 of file config.h.
.SS "#define HAVE_STDINT_H   1"
.PP
Definition at line 30 of file config.h.
.SS "#define HAVE_STDLIB_H   1"
.PP
Definition at line 33 of file config.h.
.SS "#define HAVE_STRING_H   1"
.PP
Definition at line 39 of file config.h.
.SS "#define HAVE_STRINGS_H   1"
.PP
Definition at line 36 of file config.h.
.SS "#define HAVE_SYS_STAT_H   1"
.PP
Definition at line 42 of file config.h.
.SS "#define HAVE_SYS_TYPES_H   1"
.PP
Definition at line 45 of file config.h.
.SS "#define HAVE_UNISTD_H   1"
.PP
Definition at line 48 of file config.h.
.SS "#define LT_OBJDIR   '.libs/'"
.PP
Definition at line 52 of file config.h.
.SS "#define PACKAGE   'libcgeneric'"
.PP
Definition at line 58 of file config.h.
.SS "#define PACKAGE_BUGREPORT   'villmow@gmail.com'"
.PP
Definition at line 61 of file config.h.
.SS "#define PACKAGE_NAME   'libcgeneric'"
.PP
Definition at line 64 of file config.h.
.SS "#define PACKAGE_STRING   'libcgeneric 0.4.2'"
.PP
Definition at line 67 of file config.h.
.SS "#define PACKAGE_TARNAME   'libcgeneric'"
.PP
Definition at line 70 of file config.h.
.SS "#define PACKAGE_URL   ''"
.PP
Definition at line 73 of file config.h.
.SS "#define PACKAGE_VERSION   '0.4.2'"
.PP
Definition at line 76 of file config.h.
.SS "#define STDC_HEADERS   1"
.PP
Definition at line 79 of file config.h.
.SS "#define VERSION   '0.4.2'"
.PP
Definition at line 82 of file config.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
