.TH "DequeList" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DequeList \- 
.PP
the deque object that handles the objects and is based on a generic list data structure  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <deque.h>\fP
.SH "Detailed Description"
.PP 
the deque object that handles the objects and is based on a generic list data structure 

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
