.TH "List" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
List \- 
.PP
The list object that handles the list structure.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list.h>\fP
.SH "Detailed Description"
.PP 
The list object that handles the list structure. 

.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
