.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/tests/openhash_test.c" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/tests/openhash_test.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include 'hashtable.h'\fP
.br
\fC#include 'gen/error_macros.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRUNS\fP   10000"
.br
.ti -1c
.RI "#define \fBBOUND\fP   10000"
.br
.ti -1c
.RI "#define \fBNUMCASES\fP   3"
.br
.ti -1c
.RI "#define \fBCAPACITY\fP   1000000"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int32_t \fBinthash\fP (void *, size_t)"
.br
.ti -1c
.RI "void \fBprint_hash\fP (const void *a)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define BOUND   10000"
.PP
Definition at line 8 of file openhash_test.c.
.SS "#define CAPACITY   1000000"
.PP
Definition at line 10 of file openhash_test.c.
.SS "#define NUMCASES   3"
.PP
Definition at line 9 of file openhash_test.c.
.SS "#define RUNS   10000"
.PP
Definition at line 7 of file openhash_test.c.
.SH "Function Documentation"
.PP 
.SS "int32_t inthash (void *a, size_tlen)"
.SS "int main (void)"
.PP
Definition at line 14 of file openhash_test.c.
.SS "void print_hash (const void *a)"
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
