.TH "/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/src/priority_queue.c" 3 "Mon Aug 15 2011" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Sourcecode/libgenc/branches/riolo/trunk/src/priority_queue.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'priority_queue.h'\fP
.br
\fC#include 'heap.h'\fP
.br
\fC#include 'gen/gen_macros.h'\fP
.br
\fC#include 'gen/error_macros.h'\fP
.br
\fC#include 'gen/function_macros.h'\fP
.br
\fC#include 'gen/control_arr_macros.h'\fP
.br
\fC#include 'gen/function_signatures.h'\fP
.br
\fC#include <limits.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <string.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPrioNode\fP * \fBfind_data_PrioQueue\fP (\fBPrioQueue\fP *obj, void *data, size_t datasize)"
.br
.ti -1c
.RI "int \fBpriocmp\fP (const void *a, const void *b, size_t size)"
.br
.ti -1c
.RI "\fBF_CONSTRUCT\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_CONSTRUCT_FUNC\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_DESTRUCT\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_CLEAR\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_PRINT\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_EMPTY\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SIZE\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_DUMP\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SET_COMPARE\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SET_PRINT\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SET_ALLOC\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SET_DEALLOC\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SET_COPY\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "\fBF_SIZE_OF\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "int8_t \fBinsert_PrioQueue\fP (\fBPrioQueue\fP *obj, int32_t priority, void *data, size_t datasize)"
.br
.ti -1c
.RI "\fBF_DUPLICATE\fP (\fBPrioQueue\fP)"
.br
.ti -1c
.RI "void * \fBtop_data_PrioQueue\fP (\fBPrioQueue\fP *obj)"
.br
.RI "\fIretrieves the data of the top item in the queue \fP"
.ti -1c
.RI "int32_t \fBtop_prio_PrioQueue\fP (\fBPrioQueue\fP *obj)"
.br
.RI "\fIretrieves the priority of the top item in the queue \fP"
.ti -1c
.RI "int8_t \fBpop_PrioQueue\fP (\fBPrioQueue\fP *obj)"
.br
.RI "\fIpops the item that is at the top of the queue \fP"
.ti -1c
.RI "int8_t \fBinc_prio_PrioQueue\fP (\fBPrioQueue\fP *obj, int32_t amt, void *data, size_t datasize)"
.br
.RI "\fIincrement the priority of the given data \fP"
.ti -1c
.RI "int8_t \fBdec_prio_PrioQueue\fP (\fBPrioQueue\fP *obj, int32_t amt, void *data, size_t datasize)"
.br
.RI "\fIdecrement the priority of the given data \fP"
.ti -1c
.RI "int32_t \fBfind_prio_PrioQueue\fP (\fBPrioQueue\fP *obj, void *data, size_t datasize)"
.br
.ti -1c
.RI "int8_t \fBresize_PrioQueue\fP (\fBPrioQueue\fP *obj, size_t size)"
.br
.RI "\fIResizes the Priority Queue. \fP"
.ti -1c
.RI "int \fBpriocmp\fP (const void *a, const void *b, size_t UNUSED size)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int8_t dec_prio_PrioQueue (\fBPrioQueue\fP *obj, int32_tamt, void *data, size_tdatasize)"
.PP
decrement the priority of the given data \fBParameters:\fP
.RS 4
\fIobj\fP the object that contains the data 
.br
\fIamt\fP the amount to decrement the priority by 
.br
\fIdata\fP the data to decrease priority of 
.br
\fIdatasize\fP the size of the data 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, non-zero on error 
.RE
.PP

.PP
Definition at line 168 of file priority_queue.c.
.SS "F_CLEAR (\fBPrioQueue\fP)"
.PP
Definition at line 48 of file priority_queue.c.
.SS "F_CONSTRUCT (\fBPrioQueue\fP)"
.PP
Definition at line 22 of file priority_queue.c.
.SS "F_CONSTRUCT_FUNC (\fBPrioQueue\fP)"
.PP
Definition at line 33 of file priority_queue.c.
.SS "F_DESTRUCT (\fBPrioQueue\fP)"
.PP
Definition at line 39 of file priority_queue.c.
.SS "F_DUMP (\fBPrioQueue\fP)"
.PP
Definition at line 70 of file priority_queue.c.
.SS "F_DUPLICATE (\fBPrioQueue\fP)"
.PP
Definition at line 120 of file priority_queue.c.
.SS "F_EMPTY (\fBPrioQueue\fP)"
.PP
Definition at line 59 of file priority_queue.c.
.SS "F_PRINT (\fBPrioQueue\fP)"
.PP
Definition at line 54 of file priority_queue.c.
.SS "F_SET_ALLOC (\fBPrioQueue\fP)"
.PP
Definition at line 85 of file priority_queue.c.
.SS "F_SET_COMPARE (\fBPrioQueue\fP)"
.PP
Definition at line 75 of file priority_queue.c.
.SS "F_SET_COPY (\fBPrioQueue\fP)"
.PP
Definition at line 95 of file priority_queue.c.
.SS "F_SET_DEALLOC (\fBPrioQueue\fP)"
.PP
Definition at line 90 of file priority_queue.c.
.SS "F_SET_PRINT (\fBPrioQueue\fP)"
.PP
Definition at line 80 of file priority_queue.c.
.SS "F_SIZE (\fBPrioQueue\fP)"
.PP
Definition at line 65 of file priority_queue.c.
.SS "F_SIZE_OF (\fBPrioQueue\fP)"
.PP
Definition at line 100 of file priority_queue.c.
.SS "\fBPrioNode\fP* find_data_PrioQueue (\fBPrioQueue\fP *obj, void *data, size_tdatasize)"
.SS "int32_t find_prio_PrioQueue (\fBPrioQueue\fP *obj, void *data, size_tdatasize)"
.PP
Definition at line 183 of file priority_queue.c.
.SS "int8_t inc_prio_PrioQueue (\fBPrioQueue\fP *obj, int32_tamt, void *data, size_tdatasize)"
.PP
increment the priority of the given data \fBParameters:\fP
.RS 4
\fIobj\fP the object that contains the data 
.br
\fIamt\fP the amount to increment the priority by 
.br
\fIdata\fP the data to increase the priority of 
.br
\fIdatasize\fP the size of the data 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, non-zero on error 
.RE
.PP

.PP
Definition at line 153 of file priority_queue.c.
.SS "int8_t insert_PrioQueue (\fBPrioQueue\fP *obj, int32_tpriority, void *data, size_tdatasize)"\fBParameters:\fP
.RS 4
\fIobj\fP the object to insert the items in 
.br
\fIpriority\fP the priority of the data 
.br
\fIdata\fP the data to be inserted 
.br
\fIdatasize\fP the size of the data 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, non-zero on error 
.RE
.PP

.PP
Definition at line 106 of file priority_queue.c.
.SS "int8_t pop_PrioQueue (\fBPrioQueue\fP *obj)"
.PP
pops the item that is at the top of the queue \fBParameters:\fP
.RS 4
\fIobj\fP the object to pop the top item off of 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, non-zero on error 
.RE
.PP

.PP
Definition at line 148 of file priority_queue.c.
.SS "int priocmp (const void *a, const void *b, size_tsize)"
.SS "int priocmp (const void *a, const void *b, size_t UNUSEDsize)"
.PP
Definition at line 223 of file priority_queue.c.
.SS "int8_t resize_PrioQueue (\fBPrioQueue\fP *obj, size_tsize)"
.PP
Resizes the Priority Queue. \fBParameters:\fP
.RS 4
\fIobj\fP the object to resize 
.br
\fIize\fP the size to resize the object to 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, non-zero on error 
.RE
.PP

.PP
Definition at line 197 of file priority_queue.c.
.SS "void* top_data_PrioQueue (\fBPrioQueue\fP *obj)"
.PP
retrieves the data of the top item in the queue \fBParameters:\fP
.RS 4
\fIobj\fP the object to retrieve the data of 
.RE
.PP
\fBReturns:\fP
.RS 4
data of the top item or NULL on error 
.RE
.PP

.PP
Definition at line 132 of file priority_queue.c.
.SS "int32_t top_prio_PrioQueue (\fBPrioQueue\fP *obj)"
.PP
retrieves the priority of the top item in the queue \fBParameters:\fP
.RS 4
\fIobj\fP the object to retrieve the top priority of 
.RE
.PP
\fBReturns:\fP
.RS 4
priority of top object or INT_MIN on error 
.RE
.PP

.PP
Definition at line 140 of file priority_queue.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
