.TH "/Users/matthieuriolo/Downloads/libgenc/branches/riolo/trunk/include/queue.h" 3 "Wed Jan 11 2012" ""c generic library"" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/matthieuriolo/Downloads/libgenc/branches/riolo/trunk/include/queue.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gen/data_types.h'\fP
.br
\fC#include 'gen/gen_macros.h'\fP
.br
\fC#include 'gen/function_macros.h'\fP
.br
\fC#include 'gen/function_signatures.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBQUEUELIST_DEFINED\fP"
.br
.ti -1c
.RI "#define \fBQUEUELIST_ITER_DEFINED\fP"
.br
.RI "\fIthe iterator object that helps traverse the queue \fP"
.ti -1c
.RI "#define \fBconvert_QueueList\fP(A, B, C, D)   push_QueueList((A),(B),(C),(D))"
.br
.ti -1c
.RI "#define \fBQUEUEVECTOR_DEFINED\fP"
.br
.ti -1c
.RI "#define \fBQUEUEVECTOR_ITER_DEFINED\fP"
.br
.ti -1c
.RI "#define \fBconvert_QueueVector\fP(A, B, C, D)   push_QueueVector((A),(B),(C),(D))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_ptr_struct\fP \fBQueueList\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB_ptr_iter\fP \fBITER\fP (\fBQueueList\fP)"
.br
.ti -1c
.RI "void * \fBfront_QueueList\fP (\fBQueueList\fP *queue)"
.br
.RI "\fIreturns a pointer to the front object so that it can be easily referenced \fP"
.ti -1c
.RI "int8_t \fBpush_QueueList\fP (\fBQueueList\fP *queue, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.RI "\fIpushes an item onto the end of a queue \fP"
.ti -1c
.RI "\fBcreate_iter_prototypes\fP (\fBQueueList\fP) typedef struct \fB_array_struct\fP \fBQueueVector\fP"
.br
.ti -1c
.RI "struct \fB_array_iter\fP \fBITER\fP (\fBQueueVector\fP)"
.br
.ti -1c
.RI "\fBCOMMON_FUNCTION_PROTOTYPES\fP (\fBQueueVector\fP) int8_t pop_QueueVector(\fBQueueVector\fP *queue)"
.br
.ti -1c
.RI "void * \fBfront_QueueVector\fP (\fBQueueVector\fP *queue)"
.br
.ti -1c
.RI "int8_t \fBpush_QueueVector\fP (\fBQueueVector\fP *queue, void *\fBobj\fP, size_t \fBobjsize\fP, int \fBflag\fP)"
.br
.ti -1c
.RI "int8_t \fBresize_QueueVector\fP (\fBQueueVector\fP *queue, size_t size)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define convert_QueueList(A, B, C, D)   push_QueueList((A),(B),(C),(D))"
.PP
Definition at line 66 of file queue.h.
.SS "#define convert_QueueVector(A, B, C, D)   push_QueueVector((A),(B),(C),(D))"
.PP
Definition at line 88 of file queue.h.
.SS "#define QUEUELIST_DEFINED"
.PP
Definition at line 22 of file queue.h.
.SS "#define QUEUELIST_ITER_DEFINED"
.PP
the iterator object that helps traverse the queue 
.PP
Definition at line 31 of file queue.h.
.SS "#define QUEUEVECTOR_DEFINED"
.SS "#define QUEUEVECTOR_ITER_DEFINED"
.PP
Definition at line 77 of file queue.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_ptr_struct\fP \fBQueueList\fP"
.PP
Definition at line 23 of file queue.h.
.SH "Function Documentation"
.PP 
.SS "COMMON_FUNCTION_PROTOTYPES (\fBQueueVector\fP)"
.SS "create_iter_prototypes (\fBQueueList\fP)"
.SS "void* front_QueueList (\fBQueueList\fP * queue)"
.PP
returns a pointer to the front object so that it can be easily referenced \fBParameters:\fP
.RS 4
\fIqueue\fP the queue to get the first item of 
.RE
.PP
\fBReturns:\fP
.RS 4
a pointer to the front object in the stack or NULL on failure 
.RE
.PP

.PP
Definition at line 101 of file queue.c.
.SS "void* front_QueueVector (\fBQueueVector\fP * queue)"
.PP
Definition at line 180 of file queue.c.
.SS "struct \fB_ptr_iter\fP ITER (\fBQueueList\fP)\fC [read]\fP"
.SS "struct \fB_array_iter\fP ITER (\fBQueueVector\fP)\fC [read]\fP"
.SS "int8_t push_QueueList (\fBQueueList\fP * queue, void * obj, size_t objsize, int flag)"
.PP
pushes an item onto the end of a queue \fBParameters:\fP
.RS 4
\fIqueue\fP the queue to push an item into 
.br
\fIobj\fP the object to add to the queue 
.br
\fIobjsize\fP the size of the object to add 
.br
\fIflag\fP the flag for the object 
.RE
.PP
\fBReturns:\fP
.RS 4
0 on success, non-zero on error 
.RE
.PP

.PP
Definition at line 59 of file queue.c.
.SS "int8_t push_QueueVector (\fBQueueVector\fP * queue, void * obj, size_t objsize, int flag)"
.PP
Definition at line 197 of file queue.c.
.SS "int8_t resize_QueueVector (\fBQueueVector\fP * queue, size_t size)"
.PP
Definition at line 210 of file queue.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for 'c generic library' from the source code.
